language: python
python:
  - 3.7
before_install:
  - pip install -U pytest
  - pip install codecov
  - pip install pytest pytest-cov
install:
  - pip install ".[test]" . # install package + test dependencies
script:
  - pytest --rootdir $TRAVIS_BUILD_DIR --cov=./ # run tests
after_success:
  - codecov # submit coverage
