language: python
python:
  - 3.7
before_install:
  - pip install -U pytest
  - pip install codecov
script:
  - pytest --rootdir $TRAVIS_BUILD_DIR  # run tests
after_success:
  - codecov # submit coverage
