language: python
python:
  - 3.7
before_install:
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependencies
script:
  - pytest --log-level=DEBUG --rootdir $TRAVIS_BUILD_DIR  # run tests
after_success:
  - codecov # submit coverage
