language: python
python:
  - 3.7
  - 3.8
before_install:
  - pip install pytest codecov pytest-cov
install:
  - pip install ".[test]" . # install package + test dependencies
script:
  - pytest --rootdir $TRAVIS_BUILD_DIR --cov=./ # run tests
after_success:
  - codecov
